spring:
  datasource:
    url: jdbc:mysql://119.29.176.5:30883/lottery?serverTimezone=Asia/Shanghai
    username: lottery
    password: lotteryPWD
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  type-aliases-package: com.iwhalecloud.lottery.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8089
  servlet:
    context-path: /lottery
logging:
  level:
    root: info
    com.iwhalecloud.lottery.mapper: debug
